server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pricingService
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/pricing/**
          filters:
            - StripPrefix=1